services:
     kernel.listener.eraseCache:
             class: HSpace\Bundle\ApiCacherBundle\EventListener\EraseCacheListener
             arguments: [ @service_container ]
                 tags:
                   - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
