services:
     kernel.listener.eraseCache:
             class: HSpace\Bundle\ApiCacherBundle\EventListener\EraseCacheListener
             scope: request
             arguments: ["@request"]
             tags:
               - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
